version: "3.1"
services:
    # server:
    #     build: ./server
    #     ports: 
    #         - "3001:3001"
    #         - "443:443"
    #     volumes:
    #         - ./server:/usr/src/app
    #     depends_on:
    #         - db
    #     links:
    #         - db
    #     restart: on-failure
    #     networks:
    #         - default
    # client:
    #     build: ./client
    #     ports: 
    #         - "3000:3000"
    #     volumes:
    #         - ./client:/usr/src/client
    db:
        build: ./db
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - TZ=Africa/Casablanca
        volumes:
            - persistent:/var/lib/mysql
        networks:
            - default
        cap_add:
            - SYS_NICE 
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: pikala
            MYSQL_PASSWORD: pikala
volumes:
    persistent: